version: '3.3'
services:
  db:
    container_name: devbook_db
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5000:5000'
    expose:
      # Opens port 3306 on the container
      - '5000'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Name of the volume responsible for persisting the database
volumes:
  my-db: